apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: vote
  labels:
    app: vote
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: "vote-service"
  selector:
    app: vote
